Updated Odin version
Seemed to have consistent preservation of state when I close unity and then re-open it; however, need to spawn several times in order to get back my complete states and was getting an odd error in Unity relating to Odin when I clicked on the HexSpawner in Editor

InvalidOperationException: Collection was modified; enumeration operation may not execute.